name: Android CI

on: [pull_request]

jobs:
  build:

    env: 
      working-directory: src-mobile-app

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: ${{env.working-directory}}
    - name: Execute unit tests
      run: ./gradlew test
      working-directory: ${{env.working-directory}}